#!/usr/bin/env bash

rm -rf dist && mkdir dist
cd www || exit 1
cp index.html ../dist
for tool in */ ; do
    cd "${tool}" || exit 1
    pwd
    mkdir "../../dist/${tool}"
    ./run || cp -r ./* "../../dist/${tool}"
    cd ..
done
