#!/usr/bin/env bash

rm -rf dist && mkdir dist
cd www || exit 1
cp index.html ../dist
for tool in */ ; do
    cd "${tool}" || exit 1
    pwd
    mkdir "../../dist/${tool}"
    if [ -f run ] ; then
        ./run || exit 1
    else
        cp -vr ./* "../../dist/${tool}"
    fi
    cd ..
done
